### PR TITLE
refactor: remove alejandra in favor of nixfmt

### PR DESCRIPTION
**Pull request by ashuramaruzxc**
## Changes
- rephrased: `flake.nix` description to something more suitable
- update: use [nixos-unstable](https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents) branch instead of `master` branch
- refactor: moved inputs's nixpkgs redeclaration
- refactor: removed alejandra as formatter in favor of nixfmt

### CODE REVIEW

**Comment by ashuramaruzxc** [comment]
Small suggestion @bigshaq9999, the reason why your programs have broken xdg-open native filepicker is because i don't see enabled xdg.portal option in your configuration at all. With your approval i can add it, as well as fix some gtk2,3/electron apps that use default outdated gtk3 filepicker instead of the native one(i'm talking about programs like firefox and vscode int this case)

**Review by nanachi-gh — APPROVED** [review]
poland

**Comment by nanachi-gh** [comment]
> Small suggestion @bigshaq9999, the reason why your programs have broken xdg-open native filepicker is because i don't see enabled xdg.portal option in your configuration at all. With your approval i can add it, as well as fix some gtk2,3/electron apps that use default outdated gtk3 filepicker instead of the native one(i'm talking about programs like firefox and vscode int this case)

Hello, @ashuramaruzxc,

I see. This has been an inconvenience for me for a while. I approve the addition of the options in my configuration. 

Thank you,

**Comment by ashuramaruzxc** [comment]
@bigshaq9999 I see. I will open a new PR then with those changes a bit later

**Pull request merged**
